language: r
cache: packages
latex: false
fortran: false
pandoc: false

matrix:
  include:
    - dist: trusty
    - dist: xenial
    - os: osx
      brew_packages: zeromq
    - os: osx
      osx_image: xcode10.1
      disable_homebrew: true
      r_check_args: ""

addons:
  apt:
    packages:
      - libzmq3-dev
